config/routes.rb
Rails.application.routes.draw do
  
  get "home/index"
  root "home#index"

  resources :tickets
  resources :escavators

  namespace :api do
    namespace :v1 do
      resources :tickets, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/excavator.rb
class Excavator < ApplicationRecord
  belongs_to :ticket
end

app/models/ticket.rb
class Ticket < ApplicationRecord
	has_one :excavator
end

app/controllers/api/v1/tickets_controller.rb
module Api
	module V1
		class TicketsController < ApplicationController
          skip_before_action :verify_authenticity_token

          def create
          	begin
	          @data = params
	        
	          find_ticket_attributes
	          find_excavator_attributes
	          ticket = Ticket.create(@ticket_attributes)
		      Excavator.create(@excavator_attributes.merge(ticket_id: ticket.id))

		      render json: { success: true }, status: :created
		   
          	rescue StandardError => e
          	  render json: { error: e.message }, status: :unprocessable_entity
          	end
          	
          end

          def find_ticket_attributes
          	@ticket_attributes = {
			  "request_number" => @data["RequestNumber"],
			  "sequence_number" => @data["SequenceNumber"],
			  "request_type" => @data["RequestType"],
			  "request_action" => @data["RequestAction"],
			  "response_due_date_time" => @data["DateTimes"]["ResponseDueDateTime"],
			  "sacode" => @data["ServiceArea"]["PrimaryServiceAreaCode"]["SACode"],
			  "additional_sacodes" => @data["ServiceArea"]["AdditionalServiceAreaCodes"]["SACode"],
			  "well_known_text" => @data["ExcavationInfo"]["DigsiteInfo"]["WellKnownText"]
			}
          end

          def find_excavator_attributes
			excavator = @data["Excavator"]
			@excavator_attributes = {
			  "company_name" => excavator["CompanyName"],
			  "address" => "#{excavator['Address']}, #{excavator['City']}, #{excavator['State']}, #{excavator['Zip']}",
			  "crew_on_site" => excavator["CrewOnsite"]
			}
		  end
		end
		
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/escavators_controller.rb
class EscavatorsController < ApplicationController
  def show
    @ticket = Ticket.find_by_id(id: params[:id])
    @escavator = @ticket.escavator
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 def index
   @home = "Find all saved ticket details."
 end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
    @tickets = Ticket.all
  end

  def show
    puts"===params==="+params.inspect
    @ticket = Ticket.find(params[:id])
    puts"===@ticket==="+@ticket.inspect
  end
end

app/helpers/api/v1/tickets_helper.rb
module Api::V1::TicketsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/escavators_helper.rb
module EscavatorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/escavators/show.html.erb
<h1>Escavators#show</h1>
<p>Find me in app/views/escavators/show.html.erb</p>

app/views/home/index.html.erb
Welcome to Geo data...!

 <div class="empty-data-div" style="position:relative;margin-top: 25px;">
 	<%= @home %>
 	<%= link_to "Click here", tickets_url %>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GeoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tickets/index.html.erb
<h1>Tickets</h1>
<ul>
<% if @tickets.present? %>
  <% @tickets.each do |ticket| %>
    <li><%= link_to ticket.request_number, ticket_path(ticket) %></li>
  <% end %>
  <% else %>
    <h2>Data is not available</h2>
  <%end%>
</ul>

app/views/tickets/show.html.erb
<h1>Ticket: <%= @ticket.request_number %></h1>
<p>
  <strong>Request Type:</strong>
  <%= @ticket.request_type %>
</p>
<p>
  <strong>Excavator Info:</strong>
  <%= @ticket.excavator.company_name %>
</p>
<!-- Add map here -->
<div data-controller="map">
  <div data-map-well-known-text="<%= @ticket.well_known_text %>"></div>
</div>